language: node_js
node_js:
- '0.12'
- 'iojs'
matrix:
  allow_failures:
  - node_js: 'iojs'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
after_script:
- npm run test:coverage
cache:
  directories:
  - node_modules
